apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - name: reservations
          image: microservice-app-reservations:latest
          imagePullPolicy: Never  
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://root:example@mongo:27017
